version: "3"

services:
  backend:
    build:
      dockerfile: Dockerfile.dev
      context: ./
    volumes:
      - /app/node_modules
      - ./:/app
    expose: 
      - 80
    environment:
      - DATABASE_URL=YOUR_MONGODB_DATABASE_CONNECTION_URL
      - NUM_KEYS=5
