version: "3"

services:
  backend:
    build:
      dockerfile: Dockerfile.dev
      context: ./
    volumes:
      - /app/node_modules
      - ./:/app
    ports: 
      - '5000:5000'
    environment:
      - PORT=5000
      - DATABASE_URL=YOUR_MONGODB_DATABASE_CONNECTION_URL
      - NUM_KEYS=5
